// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Street  string `json:"street"`
	Suite   string `json:"suite"`
	City    string `json:"city"`
	Zipcode string `json:"zipcode"`
	Geo     *Geo   `json:"geo"`
}

type Comment struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Body      string `json:"body"`
	PostID    int    `json:"postId"`
	CreatedAt string `json:"createdAt"`
}

type Company struct {
	Name        string `json:"name"`
	CatchPhrase string `json:"catchPhrase"`
	Bs          string `json:"bs"`
}

type Geo struct {
	Lat string `json:"lat"`
	Lng string `json:"lng"`
}

type Post struct {
	ID        int        `json:"id"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	URL       string     `json:"url"`
	Type      string     `json:"type"`
	UserID    int        `json:"userId"`
	CreatedAt string     `json:"createdAt"`
	Comments  []*Comment `json:"comments"`
}

type Todo struct {
	ID        int    `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
	UserID    int    `json:"userId"`
	User      *User  `json:"user"`
}

type User struct {
	ID        int      `json:"id"`
	Name      string   `json:"name"`
	Username  string   `json:"username"`
	Email     string   `json:"email"`
	Photo     string   `json:"photo"`
	Website   string   `json:"website"`
	CreatedAt string   `json:"createdAt"`
	Address   *Address `json:"address"`
	Company   *Company `json:"company"`
	Posts     []*Post  `json:"posts"`
}
